# Generated by Django 4.2.7 on 2023-12-01 15:03

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=1, upload_to=accounts.models.image_upload, verbose_name='الصورة الشخصية :'),
            preserve_default=False,
        ),
    ]
