# Generated by Django 4.2.7 on 2023-12-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_gender_profile_join_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, choices=[('الجلدية', 'الجلدية'), ('أسنان', 'أسنان'), ('نفسي', 'نفسي'), ('اطفال حديثي الولادة', 'اطفال حديثي الولادة'), ('نساء و توليد', 'نساء و توليد')], max_length=50, null=True, verbose_name='دكتور ؟'),
        ),
    ]
