# Generated by Django 4.2.7 on 2023-12-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='waiting_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='مدة الانتظار :'),
        ),
    ]
