# Generated by Django 4.2.7 on 2023-12-06 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_profile_image_alter_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
